language: php
 
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e "DROP DATABASE IF EXISTS wptest;" -uroot
  - bash ./bin/install-wp-tests.sh wptest wptest wptest 
 
script: phpunit
