language: php
 
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -e "CREATE DATABASE IF NOT EXISTS wptest;" -uroot
  - mysql -e "CREATE USER 'wptest'@'localhost'";
  - mysql -e "SET password FOR 'wptest'@'localhost' = password('wptest')";
  - mysql -e "GRANT ALL ON wptest.* TO 'wptest'@'localhost'";
  - sh ./bin/install-wp-tests.sh wptest wptest wptest localhost latest 
 
script: phpunit
